kind: ConfigMap
apiVersion: v1
metadata:
  name: training-config
  namespace: fine-tuning
data:
  config.json: |
    {
      "accelerate_launch_args": {
            "main_process_ip": "kfto-demo-master-0",
            "main_process_port": 29500,
            "num_processes": 2,
            "num_machines": 2,
            "machine_rank": 0,
            "mixed_precision": "no",
            "use_fsdp": "true",
            "fsdp_sharding_strategy": 1,
            "rdzv_backend": "c10d"
        },
      "model_name_or_path": "Qwen/Qwen2.5-7B-Instruct",
      "training_data_path": "/data/input/train-00000-of-00001.parquet",
      "output_dir": "/data/output/tuning/qwen2.5-tuning",
      "save_model_dir": "/data/output/model",
      "num_train_epochs": 3,
      "per_device_train_batch_size": 1,
      "per_device_eval_batch_size": 1,
      "gradient_accumulation_steps": 8,
      "packing": "True",
      "gradient_checkpointing": "True",
      "save_strategy": "epoch",
      "learning_rate": 2e-05,
      "lr_scheduler_type": "constant",
      "include_tokens_per_second": true,
      "data_formatter_template": "### Question:\n{{question}}\n\n### Answer:\n{{answer}}<|im_end|>",
      "response_template": "### Answer:\n",
      "logging_strategy": "steps",
      "logging_steps": 0.2,
      "neftune_noise_alpha": 5,
      "use_flash_attn": true,
      "use_liger_kernel": "True",
      "trackers": ["aim"],
      "experiment": "my-first-experiment",
      "aim_remote_server_ip": "aim.aim.svc.cluster.local",
      "aim_remote_server_port": "53800"
    }

